### ISSUE TITLE
Linkify throws an exception when there's no HttpContext

### ISSUE THREAD

**Issue by tsmith-sdm** [NickCraver/StackExchange.Exceptional#78]
Linkify throws an exception when there's no HttpContext where it tries to access the SiteUrl for example in a background thread.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at StackExchange.Exceptional.Email.ErrorEmail.Linkify(String s) in C:\BuildAgent\work\d20fce4a5bb47bd3\Email\ErrorEmail.cshtml:line 111
   at StackExchange.Exceptional.Email.ErrorEmail.Execute() in C:\BuildAgent\work\d20fce4a5bb47bd3\Email\ErrorEmail.cshtml:line 160
   at StackExchange.Exceptional.RazorPageBase.TransformText() in C:\BuildAgent\work\d20fce4a5bb47bd3\StackExchange.Exceptional\RazorPage.cs:line 57
   at StackExchange.Exceptional.Email.ErrorEmailer.GetErrorHtml(Error error) in C:\BuildAgent\work\d20fce4a5bb47bd3\StackExchange.Exceptional\Email\ErrorEmailer.cs:line 112
   at StackExchange.Exceptional.Email.ErrorEmailer.SendMail(Error error) in C:\BuildAgent\work\d20fce4a5bb47bd3\StackExchange.Exceptional\Email\ErrorEmailer.cs:line 74
```

**Comment by NickCraver** [comment]
This is fixed in the v2 branch (totally different encoding approach) - will close this out when it's in master and available on NuGet.

**Comment by NickCraver** [comment]
We've merged into master - and in the coming weeks we'll be on MyGet and NuGet as well - closing this out to clean up :)
